const samples={"llm-api":{message:"请用三点解释 AI Agent 的核心能力。",mode:"text",stream:true},"prompt-context":{task:"根据资料说明为什么需要上下文裁剪。",context:"输入上下文会影响模型延迟和成本。与任务无关的信息会分散模型注意力。"}};
let demos=[],currentDemo="llm-api";
const $=(selector)=>document.querySelector(selector),nav=$("#demo-nav"),form=$("#request-form"),title=$("#demo-title"),phase=$("#phase-label"),summary=$("#response-summary"),content=$("#response-content"),raw=$("#raw-response"),rawJSON=$("#raw-json");
const escapeHTML=(value)=>value.replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[character]);
const descriptor=()=>demos.find((demo)=>demo.id===currentDemo);
function clearOutput(){summary.textContent="等待请求。";content.innerHTML="";raw.hidden=true;rawJSON.textContent="";}
function setRaw(value){raw.hidden=false;rawJSON.textContent=JSON.stringify(value,null,2);}
function metadataView(metadata={}){return `<div class="metadata">${["model","latency_ms","trace_id"].filter((key)=>metadata[key]!=null).map((key)=>`<span>${key}: ${escapeHTML(String(metadata[key]))}</span>`).join("")}</div>`;}
function renderNav(){nav.innerHTML="";demos.forEach((demo)=>{const button=document.createElement("button");button.className=`nav-item${demo.id===currentDemo?" active":""}`;button.textContent=demo.name;button.onclick=()=>{currentDemo=demo.id;render();};nav.append(button);});}
function actions(){return `<div class="form-actions"><button class="primary" type="submit">发送请求</button></div>`;}
function render(){const demo=descriptor();renderNav();title.textContent=demo.name.replace(/^\d+\.\s*/,"");phase.textContent=`阶段 ${demo.name.match(/^\d+/)?.[0]||""}`;clearOutput();if(demo.id==="llm-api"){form.innerHTML=`<div class="field"><label for="message">用户消息</label><textarea id="message">${samples[demo.id].message}</textarea></div><div class="field"><label for="mode">输出模式</label><select id="mode"><option value="text">文本</option><option value="json">JSON</option></select></div><label class="option-row"><input id="stream" type="checkbox" checked>使用 SSE 流式显示</label><p class="hint">流式模式会逐段显示模型输出；关闭后展示完整 JSON 响应。</p>${actions()}`;}else{form.innerHTML=`<div class="field"><label for="task">任务</label><textarea id="task" class="compact">${samples[demo.id].task}</textarea></div><div class="field"><label for="context">参考上下文</label><textarea id="context">${samples[demo.id].context}</textarea></div><p class="hint">同一任务会运行两个 Prompt 版本，并展示各自输出。</p>${actions()}`;}form.onsubmit=submit;}
function renderResponse(response){summary.textContent="请求完成。";if(response.result?.comparisons){content.innerHTML=response.result.comparisons.map((item)=>`<article class="comparison"><h4>${escapeHTML(item.name)} <small>${escapeHTML(item.version)}</small></h4><div class="output">${escapeHTML(item.output)}</div>${metadataView({latency_ms:item.latency_ms})}</article>`).join("")+metadataView(response.metadata);}else{const value=typeof response.result==="string"?response.result:JSON.stringify(response.result,null,2);content.innerHTML=`<div class="result-text">${escapeHTML(value)}</div>${metadataView(response.metadata)}`;}setRaw(response);}
function renderError(response){summary.textContent="请求未完成。";content.innerHTML=`<div class="error"><strong>${escapeHTML(response.code||"request_failed")}</strong><br>${escapeHTML(response.error||"请求失败")}</div>${metadataView(response.metadata)}`;setRaw(response);}
async function requestJSON(endpoint,body){const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();response.ok?renderResponse(payload):renderError(payload);}
async function requestSSE(endpoint,body){const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok||!response.body){renderError(await response.json());return;}let text="",metadata={},buffer="";summary.textContent="正在接收 SSE 输出...";const reader=response.body.getReader(),decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split("\n\n");buffer=events.pop();events.forEach((event)=>{const type=event.match(/^event: (.+)$/m)?.[1],data=event.match(/^data: (.+)$/m)?.[1];if(!data)return;const payload=JSON.parse(data);if(type==="delta")text+=payload.delta;if(type==="completed")metadata=payload.metadata;if(type==="error")renderError(payload);content.innerHTML=`<div class="result-text">${escapeHTML(text)}</div>${metadataView(metadata)}`;});}summary.textContent="流式响应完成。";setRaw({result:text,metadata});}
async function submit(event){event.preventDefault();const demo=descriptor(),button=form.querySelector("button[type=submit]");button.disabled=true;clearOutput();summary.textContent="正在请求模型...";try{if(demo.id==="llm-api"){const body={message:$("#message").value,mode:$("#mode").value,stream:$("#stream").checked};body.stream?await requestSSE(demo.endpoint,body):await requestJSON(demo.endpoint,body);}else await requestJSON(demo.endpoint,{task:$("#task").value,context:$("#context").value});}catch(error){renderError({code:"network_error",error:error.message});}finally{button.disabled=false;}}
$("#clear-output").onclick=clearOutput;
async function boot(){try{const [catalogResponse,healthResponse]=await Promise.all([fetch("/api/catalog"),fetch("/health")]);demos=(await catalogResponse.json()).demos;const health=await healthResponse.json(),status=$("#service-status");status.textContent=health.status==="ok"?"服务正常":"服务异常";status.className=health.status==="ok"?"status ok":"status error";render();}catch(error){const status=$("#service-status");status.textContent="服务未连接";status.className="status error";summary.textContent="无法连接统一 Go 服务。";}}
boot();
